services:
  mongo:
    image: "mongo:7.0"
    command: "--replSet rs0 --bind_ip_all --quiet"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "mongo_storage:/data/db"
  mongo-rs-init:
    image: "mongo:7.0"
    depends_on:
      - mongo
    restart: on-failure
    entrypoint:
      - bash
      - "-c"
      - |
        mongosh --host mongo:27017 --eval 'try {
          rs.status().ok && quit(0)
        } catch {
          rs.initiate({
            _id: "rs0",
            version: 1,
            members: [{ _id: 0, host : "mongo:27017" }]
          })
        }'
  powersync:
    image: "journeyapps/powersync-service:latest"
    container_name: powersync
    depends_on:
      - mongo-rs-init
    command:
      - start
      - "-r"
      - unified
    restart: unless-stopped
    environment:
      - 'NODE_OPTIONS="--max-old-space-size=1000"'
      - POWERSYNC_CONFIG_PATH=/home/config/powersync.yaml
      - "PS_DATABASE_TYPE=${PS_DEMO_BACKEND_DATABASE_TYPE:-postgresql}"
      - "PS_DATABASE_URI=${PS_DATABASE_URI:-postgresql://postgres:postgres@db:5432/postgres}"
      - "PS_PORT=${PS_PORT:-4040}"
      - "PS_MONGO_URI=${PS_MONGO_URI:-mongodb://mongo:27017/my_db}"
      - "PS_SUPABASE_AUTH=${USE_SUPABASE_AUTH:-false}"
      - "PS_JWKS_URL=${PS_JWKS_URL:-http://localhost:6060/api/auth/keys}"
      - PS_BACKEND_DATABASE_URI=${PS_BACKEND_DATABASE_URI:-postgresql://postgres:postgres@db:5432/postgres}
      - PS_SUPABASE_JWT_SECRET=${PS_BACKEND_DATABASE_URI:-eMPSQu3wrHhNx3DDtOCOYwl44siTalA0}
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://147.93.116.63:${PS_PORT}/probes/liveness').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))",
        ]
      interval: 5s
      timeout: 1s
      retries: 15
    ports:
      - "${PS_PORT}:${PS_PORT}"
    volumes:
      - "./volumes/config:/home/config"
      - type: bind
        source: ./volumes/config/sync_rules.yaml
        target: /home/config/sync_rules.yaml
        content: |
          bucket_definitions:
            user_list: 
              parameters: SELECT token_parameters.user_id as user_id
              data:
                  - select * from todos where user_id = bucket.user_id
                  - select * from logs where user_id = bucket.user_id
            log_list:
              parameters: SELECT id as log_id FROM logs WHERE user_id = request.user_id()
              data:
                - SELECT * FROM notes WHERE log_id = bucket.log_id
      - type: bind
        source: ./volumes/config/powersync.yaml
        target: /home/config/powersync.yaml
        content: |-
          # yaml-language-server: $schema=../schema/schema.json
          telemetry:
            disable_telemetry_sharing: false

          replication:
            connections:
              - type: !env PS_DATABASE_TYPE
                uri: !env PS_BACKEND_DATABASE_URI
                sslmode: disable  # Options: 'verify-full', 'verify-ca', or 'disable'

          storage:
            type: mongodb
            uri: !env PS_MONGO_URI

          port: !env PS_PORT

          sync_rules:
            path: /home/config/sync_rules.yaml

          client_auth:
            supabase: true  # or false, depending on your requirement
            # supabase_jwt_secret: 
            jwks:
              keys:
                - kty: 'oct'
                  k: !env PS_SUPABASE_JWT_SECRET
                  alg: 'HS256'
            
            # jwks_uri: !env PS_JWKS_URL
            # audience: ["powersync-dev", "powersync"]

          api:
            tokens:
              - use_a_better_token_in_production
